### ISSUE TITLE
Python file encoding problem (+Solution)

### ISSUE THREAD

**Issue by Ansraer** [hurbeana/parco_anki#23]
I am having trouble when using the python file to create the merged txt files. `Path.write_text()` is called without a specified encoding, which causes my pc to struggle with some characters.

I am not on my workstation so I can't create the PR myself, but replacing the last two lines with:;
```python
basic_outpath.write_text("\n".join(basic), encoding="utf-8")
cloze_outpath.write_text("\n".join(cloze), encoding="utf-8")
```
should fix the problem.

**Comment by hurbeana** [comment]
Thank you very much, kinda forgot about encoding! I will fix this as soon as I'm on my PC.
