### ISSUE TITLE
Cards: Shared Memory

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/parco_anki#5]
We will need to write some cards for the "Shared Memory" slides. Anyone up for the task can assign this issue to him/herself.

**Comment by Benjaminimal** [comment]
I will start working on this one.

**Comment by hurbeana** [comment]
Thank you! I'll assign you to this issue, to keep track that youre working on this. You can do whatever you want on your fork, just make sure to do a PR when youre done with adding content to the shmem_*.txt files!

**Comment by hurbeana** [comment]
Great job! Thanks a lot again.
